/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as VitrineRouteImport } from './routes/vitrine'
import { Route as TrilhasRouteImport } from './routes/trilhas'
import { Route as SystemRouteImport } from './routes/system'
import { Route as SobreRouteImport } from './routes/sobre'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as RecuperarSenhaRouteImport } from './routes/recuperar-senha'
import { Route as PlanosRouteImport } from './routes/planos'
import { Route as PlanoRouteImport } from './routes/plano'
import { Route as PerfilRouteImport } from './routes/perfil'
import { Route as OnboardingRouteImport } from './routes/onboarding'
import { Route as NotificacoesRouteImport } from './routes/notificacoes'
import { Route as MinhasTrilhasRouteImport } from './routes/minhas-trilhas'
import { Route as LoginRouteImport } from './routes/login'
import { Route as FaqRouteImport } from './routes/faq'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as ContatoRouteImport } from './routes/contato'
import { Route as ConquistasRouteImport } from './routes/conquistas'
import { Route as ConfiguracoesRouteImport } from './routes/configuracoes'
import { Route as CatalogoRouteImport } from './routes/catalogo'
import { Route as CadastroRouteImport } from './routes/cadastro'
import { Route as BlogRouteImport } from './routes/blog'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SystemIndexRouteImport } from './routes/system.index'
import { Route as BlogIndexRouteImport } from './routes/blog.index'
import { Route as TrilhaSlugRouteImport } from './routes/trilha.$slug'
import { Route as SystemStatusRouteImport } from './routes/system.status'
import { Route as SystemSetupRouteImport } from './routes/system.setup'
import { Route as SystemSecurityStatusRouteImport } from './routes/system.security-status'
import { Route as SystemSchemaRouteImport } from './routes/system.schema'
import { Route as SystemOpsStatusRouteImport } from './routes/system.ops-status'
import { Route as SystemLaunchStatusRouteImport } from './routes/system.launch-status'
import { Route as ModuloSlugRouteImport } from './routes/modulo.$slug'
import { Route as InstrutorSlugRouteImport } from './routes/instrutor.$slug'
import { Route as CursoSlugRouteImport } from './routes/curso.$slug'
import { Route as CertificadoCodeRouteImport } from './routes/certificado.$code'
import { Route as BlogSlugRouteImport } from './routes/blog.$slug'
import { Route as AulaSlugRouteImport } from './routes/aula.$slug'
import { Route as AdminUsuariosRouteImport } from './routes/admin.usuarios'
import { Route as AdminTrilhasRouteImport } from './routes/admin.trilhas'
import { Route as AdminQuestoesRouteImport } from './routes/admin.questoes'
import { Route as AdminModulosRouteImport } from './routes/admin.modulos'
import { Route as AdminCursosRouteImport } from './routes/admin.cursos'
import { Route as AdminCertificadosRouteImport } from './routes/admin.certificados'
import { Route as AdminAiStudioRouteImport } from './routes/admin.ai-studio'
import { Route as AuthenticatedMeusCursosRouteImport } from './routes/_authenticated.meus-cursos'
import { Route as AdminAiStudioIndexRouteImport } from './routes/admin.ai-studio.index'
import { Route as CursoSlugProvaRouteImport } from './routes/curso.$slug.prova'
import { Route as BlogCategoriaSlugRouteImport } from './routes/blog.categoria.$slug'
import { Route as BlogAutorSlugRouteImport } from './routes/blog.autor.$slug'
import { Route as AdminAiStudioPdfToCourseRouteImport } from './routes/admin.ai-studio.pdf-to-course'
import { Route as AdminAiStudioToolRouteImport } from './routes/admin.ai-studio.$tool'
import { Route as ApiPublicWebhooksMercadoPagoRouteImport } from './routes/api/public/webhooks/mercado-pago'
import { Route as AdminAiStudioDraftsIdRouteImport } from './routes/admin.ai-studio.drafts.$id'

const VitrineRoute = VitrineRouteImport.update({
  id: '/vitrine',
  path: '/vitrine',
  getParentRoute: () => rootRouteImport,
} as any)
const TrilhasRoute = TrilhasRouteImport.update({
  id: '/trilhas',
  path: '/trilhas',
  getParentRoute: () => rootRouteImport,
} as any)
const SystemRoute = SystemRouteImport.update({
  id: '/system',
  path: '/system',
  getParentRoute: () => rootRouteImport,
} as any)
const SobreRoute = SobreRouteImport.update({
  id: '/sobre',
  path: '/sobre',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const RecuperarSenhaRoute = RecuperarSenhaRouteImport.update({
  id: '/recuperar-senha',
  path: '/recuperar-senha',
  getParentRoute: () => rootRouteImport,
} as any)
const PlanosRoute = PlanosRouteImport.update({
  id: '/planos',
  path: '/planos',
  getParentRoute: () => rootRouteImport,
} as any)
const PlanoRoute = PlanoRouteImport.update({
  id: '/plano',
  path: '/plano',
  getParentRoute: () => rootRouteImport,
} as any)
const PerfilRoute = PerfilRouteImport.update({
  id: '/perfil',
  path: '/perfil',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingRoute = OnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => rootRouteImport,
} as any)
const NotificacoesRoute = NotificacoesRouteImport.update({
  id: '/notificacoes',
  path: '/notificacoes',
  getParentRoute: () => rootRouteImport,
} as any)
const MinhasTrilhasRoute = MinhasTrilhasRouteImport.update({
  id: '/minhas-trilhas',
  path: '/minhas-trilhas',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const FaqRoute = FaqRouteImport.update({
  id: '/faq',
  path: '/faq',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const ContatoRoute = ContatoRouteImport.update({
  id: '/contato',
  path: '/contato',
  getParentRoute: () => rootRouteImport,
} as any)
const ConquistasRoute = ConquistasRouteImport.update({
  id: '/conquistas',
  path: '/conquistas',
  getParentRoute: () => rootRouteImport,
} as any)
const ConfiguracoesRoute = ConfiguracoesRouteImport.update({
  id: '/configuracoes',
  path: '/configuracoes',
  getParentRoute: () => rootRouteImport,
} as any)
const CatalogoRoute = CatalogoRouteImport.update({
  id: '/catalogo',
  path: '/catalogo',
  getParentRoute: () => rootRouteImport,
} as any)
const CadastroRoute = CadastroRouteImport.update({
  id: '/cadastro',
  path: '/cadastro',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogRoute = BlogRouteImport.update({
  id: '/blog',
  path: '/blog',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SystemIndexRoute = SystemIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => SystemRoute,
} as any)
const BlogIndexRoute = BlogIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => BlogRoute,
} as any)
const TrilhaSlugRoute = TrilhaSlugRouteImport.update({
  id: '/trilha/$slug',
  path: '/trilha/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const SystemStatusRoute = SystemStatusRouteImport.update({
  id: '/status',
  path: '/status',
  getParentRoute: () => SystemRoute,
} as any)
const SystemSetupRoute = SystemSetupRouteImport.update({
  id: '/setup',
  path: '/setup',
  getParentRoute: () => SystemRoute,
} as any)
const SystemSecurityStatusRoute = SystemSecurityStatusRouteImport.update({
  id: '/security-status',
  path: '/security-status',
  getParentRoute: () => SystemRoute,
} as any)
const SystemSchemaRoute = SystemSchemaRouteImport.update({
  id: '/schema',
  path: '/schema',
  getParentRoute: () => SystemRoute,
} as any)
const SystemOpsStatusRoute = SystemOpsStatusRouteImport.update({
  id: '/ops-status',
  path: '/ops-status',
  getParentRoute: () => SystemRoute,
} as any)
const SystemLaunchStatusRoute = SystemLaunchStatusRouteImport.update({
  id: '/launch-status',
  path: '/launch-status',
  getParentRoute: () => SystemRoute,
} as any)
const ModuloSlugRoute = ModuloSlugRouteImport.update({
  id: '/modulo/$slug',
  path: '/modulo/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const InstrutorSlugRoute = InstrutorSlugRouteImport.update({
  id: '/instrutor/$slug',
  path: '/instrutor/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const CursoSlugRoute = CursoSlugRouteImport.update({
  id: '/curso/$slug',
  path: '/curso/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const CertificadoCodeRoute = CertificadoCodeRouteImport.update({
  id: '/certificado/$code',
  path: '/certificado/$code',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogSlugRoute = BlogSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => BlogRoute,
} as any)
const AulaSlugRoute = AulaSlugRouteImport.update({
  id: '/aula/$slug',
  path: '/aula/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminUsuariosRoute = AdminUsuariosRouteImport.update({
  id: '/usuarios',
  path: '/usuarios',
  getParentRoute: () => AdminRoute,
} as any)
const AdminTrilhasRoute = AdminTrilhasRouteImport.update({
  id: '/trilhas',
  path: '/trilhas',
  getParentRoute: () => AdminRoute,
} as any)
const AdminQuestoesRoute = AdminQuestoesRouteImport.update({
  id: '/questoes',
  path: '/questoes',
  getParentRoute: () => AdminRoute,
} as any)
const AdminModulosRoute = AdminModulosRouteImport.update({
  id: '/modulos',
  path: '/modulos',
  getParentRoute: () => AdminRoute,
} as any)
const AdminCursosRoute = AdminCursosRouteImport.update({
  id: '/cursos',
  path: '/cursos',
  getParentRoute: () => AdminRoute,
} as any)
const AdminCertificadosRoute = AdminCertificadosRouteImport.update({
  id: '/certificados',
  path: '/certificados',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAiStudioRoute = AdminAiStudioRouteImport.update({
  id: '/ai-studio',
  path: '/ai-studio',
  getParentRoute: () => AdminRoute,
} as any)
const AuthenticatedMeusCursosRoute = AuthenticatedMeusCursosRouteImport.update({
  id: '/meus-cursos',
  path: '/meus-cursos',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AdminAiStudioIndexRoute = AdminAiStudioIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminAiStudioRoute,
} as any)
const CursoSlugProvaRoute = CursoSlugProvaRouteImport.update({
  id: '/prova',
  path: '/prova',
  getParentRoute: () => CursoSlugRoute,
} as any)
const BlogCategoriaSlugRoute = BlogCategoriaSlugRouteImport.update({
  id: '/categoria/$slug',
  path: '/categoria/$slug',
  getParentRoute: () => BlogRoute,
} as any)
const BlogAutorSlugRoute = BlogAutorSlugRouteImport.update({
  id: '/autor/$slug',
  path: '/autor/$slug',
  getParentRoute: () => BlogRoute,
} as any)
const AdminAiStudioPdfToCourseRoute =
  AdminAiStudioPdfToCourseRouteImport.update({
    id: '/pdf-to-course',
    path: '/pdf-to-course',
    getParentRoute: () => AdminAiStudioRoute,
  } as any)
const AdminAiStudioToolRoute = AdminAiStudioToolRouteImport.update({
  id: '/$tool',
  path: '/$tool',
  getParentRoute: () => AdminAiStudioRoute,
} as any)
const ApiPublicWebhooksMercadoPagoRoute =
  ApiPublicWebhooksMercadoPagoRouteImport.update({
    id: '/api/public/webhooks/mercado-pago',
    path: '/api/public/webhooks/mercado-pago',
    getParentRoute: () => rootRouteImport,
  } as any)
const AdminAiStudioDraftsIdRoute = AdminAiStudioDraftsIdRouteImport.update({
  id: '/drafts/$id',
  path: '/drafts/$id',
  getParentRoute: () => AdminAiStudioRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/blog': typeof BlogRouteWithChildren
  '/cadastro': typeof CadastroRoute
  '/catalogo': typeof CatalogoRoute
  '/configuracoes': typeof ConfiguracoesRoute
  '/conquistas': typeof ConquistasRoute
  '/contato': typeof ContatoRoute
  '/dashboard': typeof DashboardRoute
  '/faq': typeof FaqRoute
  '/login': typeof LoginRoute
  '/minhas-trilhas': typeof MinhasTrilhasRoute
  '/notificacoes': typeof NotificacoesRoute
  '/onboarding': typeof OnboardingRoute
  '/perfil': typeof PerfilRoute
  '/plano': typeof PlanoRoute
  '/planos': typeof PlanosRoute
  '/recuperar-senha': typeof RecuperarSenhaRoute
  '/reset-password': typeof ResetPasswordRoute
  '/sobre': typeof SobreRoute
  '/system': typeof SystemRouteWithChildren
  '/trilhas': typeof TrilhasRoute
  '/vitrine': typeof VitrineRoute
  '/meus-cursos': typeof AuthenticatedMeusCursosRoute
  '/admin/ai-studio': typeof AdminAiStudioRouteWithChildren
  '/admin/certificados': typeof AdminCertificadosRoute
  '/admin/cursos': typeof AdminCursosRoute
  '/admin/modulos': typeof AdminModulosRoute
  '/admin/questoes': typeof AdminQuestoesRoute
  '/admin/trilhas': typeof AdminTrilhasRoute
  '/admin/usuarios': typeof AdminUsuariosRoute
  '/aula/$slug': typeof AulaSlugRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/certificado/$code': typeof CertificadoCodeRoute
  '/curso/$slug': typeof CursoSlugRouteWithChildren
  '/instrutor/$slug': typeof InstrutorSlugRoute
  '/modulo/$slug': typeof ModuloSlugRoute
  '/system/launch-status': typeof SystemLaunchStatusRoute
  '/system/ops-status': typeof SystemOpsStatusRoute
  '/system/schema': typeof SystemSchemaRoute
  '/system/security-status': typeof SystemSecurityStatusRoute
  '/system/setup': typeof SystemSetupRoute
  '/system/status': typeof SystemStatusRoute
  '/trilha/$slug': typeof TrilhaSlugRoute
  '/blog/': typeof BlogIndexRoute
  '/system/': typeof SystemIndexRoute
  '/admin/ai-studio/$tool': typeof AdminAiStudioToolRoute
  '/admin/ai-studio/pdf-to-course': typeof AdminAiStudioPdfToCourseRoute
  '/blog/autor/$slug': typeof BlogAutorSlugRoute
  '/blog/categoria/$slug': typeof BlogCategoriaSlugRoute
  '/curso/$slug/prova': typeof CursoSlugProvaRoute
  '/admin/ai-studio/': typeof AdminAiStudioIndexRoute
  '/admin/ai-studio/drafts/$id': typeof AdminAiStudioDraftsIdRoute
  '/api/public/webhooks/mercado-pago': typeof ApiPublicWebhooksMercadoPagoRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/cadastro': typeof CadastroRoute
  '/catalogo': typeof CatalogoRoute
  '/configuracoes': typeof ConfiguracoesRoute
  '/conquistas': typeof ConquistasRoute
  '/contato': typeof ContatoRoute
  '/dashboard': typeof DashboardRoute
  '/faq': typeof FaqRoute
  '/login': typeof LoginRoute
  '/minhas-trilhas': typeof MinhasTrilhasRoute
  '/notificacoes': typeof NotificacoesRoute
  '/onboarding': typeof OnboardingRoute
  '/perfil': typeof PerfilRoute
  '/plano': typeof PlanoRoute
  '/planos': typeof PlanosRoute
  '/recuperar-senha': typeof RecuperarSenhaRoute
  '/reset-password': typeof ResetPasswordRoute
  '/sobre': typeof SobreRoute
  '/trilhas': typeof TrilhasRoute
  '/vitrine': typeof VitrineRoute
  '/meus-cursos': typeof AuthenticatedMeusCursosRoute
  '/admin/certificados': typeof AdminCertificadosRoute
  '/admin/cursos': typeof AdminCursosRoute
  '/admin/modulos': typeof AdminModulosRoute
  '/admin/questoes': typeof AdminQuestoesRoute
  '/admin/trilhas': typeof AdminTrilhasRoute
  '/admin/usuarios': typeof AdminUsuariosRoute
  '/aula/$slug': typeof AulaSlugRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/certificado/$code': typeof CertificadoCodeRoute
  '/curso/$slug': typeof CursoSlugRouteWithChildren
  '/instrutor/$slug': typeof InstrutorSlugRoute
  '/modulo/$slug': typeof ModuloSlugRoute
  '/system/launch-status': typeof SystemLaunchStatusRoute
  '/system/ops-status': typeof SystemOpsStatusRoute
  '/system/schema': typeof SystemSchemaRoute
  '/system/security-status': typeof SystemSecurityStatusRoute
  '/system/setup': typeof SystemSetupRoute
  '/system/status': typeof SystemStatusRoute
  '/trilha/$slug': typeof TrilhaSlugRoute
  '/blog': typeof BlogIndexRoute
  '/system': typeof SystemIndexRoute
  '/admin/ai-studio/$tool': typeof AdminAiStudioToolRoute
  '/admin/ai-studio/pdf-to-course': typeof AdminAiStudioPdfToCourseRoute
  '/blog/autor/$slug': typeof BlogAutorSlugRoute
  '/blog/categoria/$slug': typeof BlogCategoriaSlugRoute
  '/curso/$slug/prova': typeof CursoSlugProvaRoute
  '/admin/ai-studio': typeof AdminAiStudioIndexRoute
  '/admin/ai-studio/drafts/$id': typeof AdminAiStudioDraftsIdRoute
  '/api/public/webhooks/mercado-pago': typeof ApiPublicWebhooksMercadoPagoRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/admin': typeof AdminRouteWithChildren
  '/blog': typeof BlogRouteWithChildren
  '/cadastro': typeof CadastroRoute
  '/catalogo': typeof CatalogoRoute
  '/configuracoes': typeof ConfiguracoesRoute
  '/conquistas': typeof ConquistasRoute
  '/contato': typeof ContatoRoute
  '/dashboard': typeof DashboardRoute
  '/faq': typeof FaqRoute
  '/login': typeof LoginRoute
  '/minhas-trilhas': typeof MinhasTrilhasRoute
  '/notificacoes': typeof NotificacoesRoute
  '/onboarding': typeof OnboardingRoute
  '/perfil': typeof PerfilRoute
  '/plano': typeof PlanoRoute
  '/planos': typeof PlanosRoute
  '/recuperar-senha': typeof RecuperarSenhaRoute
  '/reset-password': typeof ResetPasswordRoute
  '/sobre': typeof SobreRoute
  '/system': typeof SystemRouteWithChildren
  '/trilhas': typeof TrilhasRoute
  '/vitrine': typeof VitrineRoute
  '/_authenticated/meus-cursos': typeof AuthenticatedMeusCursosRoute
  '/admin/ai-studio': typeof AdminAiStudioRouteWithChildren
  '/admin/certificados': typeof AdminCertificadosRoute
  '/admin/cursos': typeof AdminCursosRoute
  '/admin/modulos': typeof AdminModulosRoute
  '/admin/questoes': typeof AdminQuestoesRoute
  '/admin/trilhas': typeof AdminTrilhasRoute
  '/admin/usuarios': typeof AdminUsuariosRoute
  '/aula/$slug': typeof AulaSlugRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/certificado/$code': typeof CertificadoCodeRoute
  '/curso/$slug': typeof CursoSlugRouteWithChildren
  '/instrutor/$slug': typeof InstrutorSlugRoute
  '/modulo/$slug': typeof ModuloSlugRoute
  '/system/launch-status': typeof SystemLaunchStatusRoute
  '/system/ops-status': typeof SystemOpsStatusRoute
  '/system/schema': typeof SystemSchemaRoute
  '/system/security-status': typeof SystemSecurityStatusRoute
  '/system/setup': typeof SystemSetupRoute
  '/system/status': typeof SystemStatusRoute
  '/trilha/$slug': typeof TrilhaSlugRoute
  '/blog/': typeof BlogIndexRoute
  '/system/': typeof SystemIndexRoute
  '/admin/ai-studio/$tool': typeof AdminAiStudioToolRoute
  '/admin/ai-studio/pdf-to-course': typeof AdminAiStudioPdfToCourseRoute
  '/blog/autor/$slug': typeof BlogAutorSlugRoute
  '/blog/categoria/$slug': typeof BlogCategoriaSlugRoute
  '/curso/$slug/prova': typeof CursoSlugProvaRoute
  '/admin/ai-studio/': typeof AdminAiStudioIndexRoute
  '/admin/ai-studio/drafts/$id': typeof AdminAiStudioDraftsIdRoute
  '/api/public/webhooks/mercado-pago': typeof ApiPublicWebhooksMercadoPagoRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/blog'
    | '/cadastro'
    | '/catalogo'
    | '/configuracoes'
    | '/conquistas'
    | '/contato'
    | '/dashboard'
    | '/faq'
    | '/login'
    | '/minhas-trilhas'
    | '/notificacoes'
    | '/onboarding'
    | '/perfil'
    | '/plano'
    | '/planos'
    | '/recuperar-senha'
    | '/reset-password'
    | '/sobre'
    | '/system'
    | '/trilhas'
    | '/vitrine'
    | '/meus-cursos'
    | '/admin/ai-studio'
    | '/admin/certificados'
    | '/admin/cursos'
    | '/admin/modulos'
    | '/admin/questoes'
    | '/admin/trilhas'
    | '/admin/usuarios'
    | '/aula/$slug'
    | '/blog/$slug'
    | '/certificado/$code'
    | '/curso/$slug'
    | '/instrutor/$slug'
    | '/modulo/$slug'
    | '/system/launch-status'
    | '/system/ops-status'
    | '/system/schema'
    | '/system/security-status'
    | '/system/setup'
    | '/system/status'
    | '/trilha/$slug'
    | '/blog/'
    | '/system/'
    | '/admin/ai-studio/$tool'
    | '/admin/ai-studio/pdf-to-course'
    | '/blog/autor/$slug'
    | '/blog/categoria/$slug'
    | '/curso/$slug/prova'
    | '/admin/ai-studio/'
    | '/admin/ai-studio/drafts/$id'
    | '/api/public/webhooks/mercado-pago'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/cadastro'
    | '/catalogo'
    | '/configuracoes'
    | '/conquistas'
    | '/contato'
    | '/dashboard'
    | '/faq'
    | '/login'
    | '/minhas-trilhas'
    | '/notificacoes'
    | '/onboarding'
    | '/perfil'
    | '/plano'
    | '/planos'
    | '/recuperar-senha'
    | '/reset-password'
    | '/sobre'
    | '/trilhas'
    | '/vitrine'
    | '/meus-cursos'
    | '/admin/certificados'
    | '/admin/cursos'
    | '/admin/modulos'
    | '/admin/questoes'
    | '/admin/trilhas'
    | '/admin/usuarios'
    | '/aula/$slug'
    | '/blog/$slug'
    | '/certificado/$code'
    | '/curso/$slug'
    | '/instrutor/$slug'
    | '/modulo/$slug'
    | '/system/launch-status'
    | '/system/ops-status'
    | '/system/schema'
    | '/system/security-status'
    | '/system/setup'
    | '/system/status'
    | '/trilha/$slug'
    | '/blog'
    | '/system'
    | '/admin/ai-studio/$tool'
    | '/admin/ai-studio/pdf-to-course'
    | '/blog/autor/$slug'
    | '/blog/categoria/$slug'
    | '/curso/$slug/prova'
    | '/admin/ai-studio'
    | '/admin/ai-studio/drafts/$id'
    | '/api/public/webhooks/mercado-pago'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/admin'
    | '/blog'
    | '/cadastro'
    | '/catalogo'
    | '/configuracoes'
    | '/conquistas'
    | '/contato'
    | '/dashboard'
    | '/faq'
    | '/login'
    | '/minhas-trilhas'
    | '/notificacoes'
    | '/onboarding'
    | '/perfil'
    | '/plano'
    | '/planos'
    | '/recuperar-senha'
    | '/reset-password'
    | '/sobre'
    | '/system'
    | '/trilhas'
    | '/vitrine'
    | '/_authenticated/meus-cursos'
    | '/admin/ai-studio'
    | '/admin/certificados'
    | '/admin/cursos'
    | '/admin/modulos'
    | '/admin/questoes'
    | '/admin/trilhas'
    | '/admin/usuarios'
    | '/aula/$slug'
    | '/blog/$slug'
    | '/certificado/$code'
    | '/curso/$slug'
    | '/instrutor/$slug'
    | '/modulo/$slug'
    | '/system/launch-status'
    | '/system/ops-status'
    | '/system/schema'
    | '/system/security-status'
    | '/system/setup'
    | '/system/status'
    | '/trilha/$slug'
    | '/blog/'
    | '/system/'
    | '/admin/ai-studio/$tool'
    | '/admin/ai-studio/pdf-to-course'
    | '/blog/autor/$slug'
    | '/blog/categoria/$slug'
    | '/curso/$slug/prova'
    | '/admin/ai-studio/'
    | '/admin/ai-studio/drafts/$id'
    | '/api/public/webhooks/mercado-pago'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  AdminRoute: typeof AdminRouteWithChildren
  BlogRoute: typeof BlogRouteWithChildren
  CadastroRoute: typeof CadastroRoute
  CatalogoRoute: typeof CatalogoRoute
  ConfiguracoesRoute: typeof ConfiguracoesRoute
  ConquistasRoute: typeof ConquistasRoute
  ContatoRoute: typeof ContatoRoute
  DashboardRoute: typeof DashboardRoute
  FaqRoute: typeof FaqRoute
  LoginRoute: typeof LoginRoute
  MinhasTrilhasRoute: typeof MinhasTrilhasRoute
  NotificacoesRoute: typeof NotificacoesRoute
  OnboardingRoute: typeof OnboardingRoute
  PerfilRoute: typeof PerfilRoute
  PlanoRoute: typeof PlanoRoute
  PlanosRoute: typeof PlanosRoute
  RecuperarSenhaRoute: typeof RecuperarSenhaRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  SobreRoute: typeof SobreRoute
  SystemRoute: typeof SystemRouteWithChildren
  TrilhasRoute: typeof TrilhasRoute
  VitrineRoute: typeof VitrineRoute
  AulaSlugRoute: typeof AulaSlugRoute
  CertificadoCodeRoute: typeof CertificadoCodeRoute
  CursoSlugRoute: typeof CursoSlugRouteWithChildren
  InstrutorSlugRoute: typeof InstrutorSlugRoute
  ModuloSlugRoute: typeof ModuloSlugRoute
  TrilhaSlugRoute: typeof TrilhaSlugRoute
  ApiPublicWebhooksMercadoPagoRoute: typeof ApiPublicWebhooksMercadoPagoRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/vitrine': {
      id: '/vitrine'
      path: '/vitrine'
      fullPath: '/vitrine'
      preLoaderRoute: typeof VitrineRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/trilhas': {
      id: '/trilhas'
      path: '/trilhas'
      fullPath: '/trilhas'
      preLoaderRoute: typeof TrilhasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/system': {
      id: '/system'
      path: '/system'
      fullPath: '/system'
      preLoaderRoute: typeof SystemRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sobre': {
      id: '/sobre'
      path: '/sobre'
      fullPath: '/sobre'
      preLoaderRoute: typeof SobreRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/recuperar-senha': {
      id: '/recuperar-senha'
      path: '/recuperar-senha'
      fullPath: '/recuperar-senha'
      preLoaderRoute: typeof RecuperarSenhaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/planos': {
      id: '/planos'
      path: '/planos'
      fullPath: '/planos'
      preLoaderRoute: typeof PlanosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/plano': {
      id: '/plano'
      path: '/plano'
      fullPath: '/plano'
      preLoaderRoute: typeof PlanoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/perfil': {
      id: '/perfil'
      path: '/perfil'
      fullPath: '/perfil'
      preLoaderRoute: typeof PerfilRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding': {
      id: '/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof OnboardingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/notificacoes': {
      id: '/notificacoes'
      path: '/notificacoes'
      fullPath: '/notificacoes'
      preLoaderRoute: typeof NotificacoesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/minhas-trilhas': {
      id: '/minhas-trilhas'
      path: '/minhas-trilhas'
      fullPath: '/minhas-trilhas'
      preLoaderRoute: typeof MinhasTrilhasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/faq': {
      id: '/faq'
      path: '/faq'
      fullPath: '/faq'
      preLoaderRoute: typeof FaqRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contato': {
      id: '/contato'
      path: '/contato'
      fullPath: '/contato'
      preLoaderRoute: typeof ContatoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/conquistas': {
      id: '/conquistas'
      path: '/conquistas'
      fullPath: '/conquistas'
      preLoaderRoute: typeof ConquistasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/configuracoes': {
      id: '/configuracoes'
      path: '/configuracoes'
      fullPath: '/configuracoes'
      preLoaderRoute: typeof ConfiguracoesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/catalogo': {
      id: '/catalogo'
      path: '/catalogo'
      fullPath: '/catalogo'
      preLoaderRoute: typeof CatalogoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cadastro': {
      id: '/cadastro'
      path: '/cadastro'
      fullPath: '/cadastro'
      preLoaderRoute: typeof CadastroRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog': {
      id: '/blog'
      path: '/blog'
      fullPath: '/blog'
      preLoaderRoute: typeof BlogRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/system/': {
      id: '/system/'
      path: '/'
      fullPath: '/system/'
      preLoaderRoute: typeof SystemIndexRouteImport
      parentRoute: typeof SystemRoute
    }
    '/blog/': {
      id: '/blog/'
      path: '/'
      fullPath: '/blog/'
      preLoaderRoute: typeof BlogIndexRouteImport
      parentRoute: typeof BlogRoute
    }
    '/trilha/$slug': {
      id: '/trilha/$slug'
      path: '/trilha/$slug'
      fullPath: '/trilha/$slug'
      preLoaderRoute: typeof TrilhaSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/system/status': {
      id: '/system/status'
      path: '/status'
      fullPath: '/system/status'
      preLoaderRoute: typeof SystemStatusRouteImport
      parentRoute: typeof SystemRoute
    }
    '/system/setup': {
      id: '/system/setup'
      path: '/setup'
      fullPath: '/system/setup'
      preLoaderRoute: typeof SystemSetupRouteImport
      parentRoute: typeof SystemRoute
    }
    '/system/security-status': {
      id: '/system/security-status'
      path: '/security-status'
      fullPath: '/system/security-status'
      preLoaderRoute: typeof SystemSecurityStatusRouteImport
      parentRoute: typeof SystemRoute
    }
    '/system/schema': {
      id: '/system/schema'
      path: '/schema'
      fullPath: '/system/schema'
      preLoaderRoute: typeof SystemSchemaRouteImport
      parentRoute: typeof SystemRoute
    }
    '/system/ops-status': {
      id: '/system/ops-status'
      path: '/ops-status'
      fullPath: '/system/ops-status'
      preLoaderRoute: typeof SystemOpsStatusRouteImport
      parentRoute: typeof SystemRoute
    }
    '/system/launch-status': {
      id: '/system/launch-status'
      path: '/launch-status'
      fullPath: '/system/launch-status'
      preLoaderRoute: typeof SystemLaunchStatusRouteImport
      parentRoute: typeof SystemRoute
    }
    '/modulo/$slug': {
      id: '/modulo/$slug'
      path: '/modulo/$slug'
      fullPath: '/modulo/$slug'
      preLoaderRoute: typeof ModuloSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/instrutor/$slug': {
      id: '/instrutor/$slug'
      path: '/instrutor/$slug'
      fullPath: '/instrutor/$slug'
      preLoaderRoute: typeof InstrutorSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/curso/$slug': {
      id: '/curso/$slug'
      path: '/curso/$slug'
      fullPath: '/curso/$slug'
      preLoaderRoute: typeof CursoSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/certificado/$code': {
      id: '/certificado/$code'
      path: '/certificado/$code'
      fullPath: '/certificado/$code'
      preLoaderRoute: typeof CertificadoCodeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/$slug': {
      id: '/blog/$slug'
      path: '/$slug'
      fullPath: '/blog/$slug'
      preLoaderRoute: typeof BlogSlugRouteImport
      parentRoute: typeof BlogRoute
    }
    '/aula/$slug': {
      id: '/aula/$slug'
      path: '/aula/$slug'
      fullPath: '/aula/$slug'
      preLoaderRoute: typeof AulaSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/usuarios': {
      id: '/admin/usuarios'
      path: '/usuarios'
      fullPath: '/admin/usuarios'
      preLoaderRoute: typeof AdminUsuariosRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/trilhas': {
      id: '/admin/trilhas'
      path: '/trilhas'
      fullPath: '/admin/trilhas'
      preLoaderRoute: typeof AdminTrilhasRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/questoes': {
      id: '/admin/questoes'
      path: '/questoes'
      fullPath: '/admin/questoes'
      preLoaderRoute: typeof AdminQuestoesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/modulos': {
      id: '/admin/modulos'
      path: '/modulos'
      fullPath: '/admin/modulos'
      preLoaderRoute: typeof AdminModulosRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/cursos': {
      id: '/admin/cursos'
      path: '/cursos'
      fullPath: '/admin/cursos'
      preLoaderRoute: typeof AdminCursosRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/certificados': {
      id: '/admin/certificados'
      path: '/certificados'
      fullPath: '/admin/certificados'
      preLoaderRoute: typeof AdminCertificadosRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/ai-studio': {
      id: '/admin/ai-studio'
      path: '/ai-studio'
      fullPath: '/admin/ai-studio'
      preLoaderRoute: typeof AdminAiStudioRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_authenticated/meus-cursos': {
      id: '/_authenticated/meus-cursos'
      path: '/meus-cursos'
      fullPath: '/meus-cursos'
      preLoaderRoute: typeof AuthenticatedMeusCursosRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/admin/ai-studio/': {
      id: '/admin/ai-studio/'
      path: '/'
      fullPath: '/admin/ai-studio/'
      preLoaderRoute: typeof AdminAiStudioIndexRouteImport
      parentRoute: typeof AdminAiStudioRoute
    }
    '/curso/$slug/prova': {
      id: '/curso/$slug/prova'
      path: '/prova'
      fullPath: '/curso/$slug/prova'
      preLoaderRoute: typeof CursoSlugProvaRouteImport
      parentRoute: typeof CursoSlugRoute
    }
    '/blog/categoria/$slug': {
      id: '/blog/categoria/$slug'
      path: '/categoria/$slug'
      fullPath: '/blog/categoria/$slug'
      preLoaderRoute: typeof BlogCategoriaSlugRouteImport
      parentRoute: typeof BlogRoute
    }
    '/blog/autor/$slug': {
      id: '/blog/autor/$slug'
      path: '/autor/$slug'
      fullPath: '/blog/autor/$slug'
      preLoaderRoute: typeof BlogAutorSlugRouteImport
      parentRoute: typeof BlogRoute
    }
    '/admin/ai-studio/pdf-to-course': {
      id: '/admin/ai-studio/pdf-to-course'
      path: '/pdf-to-course'
      fullPath: '/admin/ai-studio/pdf-to-course'
      preLoaderRoute: typeof AdminAiStudioPdfToCourseRouteImport
      parentRoute: typeof AdminAiStudioRoute
    }
    '/admin/ai-studio/$tool': {
      id: '/admin/ai-studio/$tool'
      path: '/$tool'
      fullPath: '/admin/ai-studio/$tool'
      preLoaderRoute: typeof AdminAiStudioToolRouteImport
      parentRoute: typeof AdminAiStudioRoute
    }
    '/api/public/webhooks/mercado-pago': {
      id: '/api/public/webhooks/mercado-pago'
      path: '/api/public/webhooks/mercado-pago'
      fullPath: '/api/public/webhooks/mercado-pago'
      preLoaderRoute: typeof ApiPublicWebhooksMercadoPagoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/ai-studio/drafts/$id': {
      id: '/admin/ai-studio/drafts/$id'
      path: '/drafts/$id'
      fullPath: '/admin/ai-studio/drafts/$id'
      preLoaderRoute: typeof AdminAiStudioDraftsIdRouteImport
      parentRoute: typeof AdminAiStudioRoute
    }
  }
}

interface AuthenticatedRouteChildren {
  AuthenticatedMeusCursosRoute: typeof AuthenticatedMeusCursosRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedMeusCursosRoute: AuthenticatedMeusCursosRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

interface AdminAiStudioRouteChildren {
  AdminAiStudioToolRoute: typeof AdminAiStudioToolRoute
  AdminAiStudioPdfToCourseRoute: typeof AdminAiStudioPdfToCourseRoute
  AdminAiStudioIndexRoute: typeof AdminAiStudioIndexRoute
  AdminAiStudioDraftsIdRoute: typeof AdminAiStudioDraftsIdRoute
}

const AdminAiStudioRouteChildren: AdminAiStudioRouteChildren = {
  AdminAiStudioToolRoute: AdminAiStudioToolRoute,
  AdminAiStudioPdfToCourseRoute: AdminAiStudioPdfToCourseRoute,
  AdminAiStudioIndexRoute: AdminAiStudioIndexRoute,
  AdminAiStudioDraftsIdRoute: AdminAiStudioDraftsIdRoute,
}

const AdminAiStudioRouteWithChildren = AdminAiStudioRoute._addFileChildren(
  AdminAiStudioRouteChildren,
)

interface AdminRouteChildren {
  AdminAiStudioRoute: typeof AdminAiStudioRouteWithChildren
  AdminCertificadosRoute: typeof AdminCertificadosRoute
  AdminCursosRoute: typeof AdminCursosRoute
  AdminModulosRoute: typeof AdminModulosRoute
  AdminQuestoesRoute: typeof AdminQuestoesRoute
  AdminTrilhasRoute: typeof AdminTrilhasRoute
  AdminUsuariosRoute: typeof AdminUsuariosRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminAiStudioRoute: AdminAiStudioRouteWithChildren,
  AdminCertificadosRoute: AdminCertificadosRoute,
  AdminCursosRoute: AdminCursosRoute,
  AdminModulosRoute: AdminModulosRoute,
  AdminQuestoesRoute: AdminQuestoesRoute,
  AdminTrilhasRoute: AdminTrilhasRoute,
  AdminUsuariosRoute: AdminUsuariosRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

interface BlogRouteChildren {
  BlogSlugRoute: typeof BlogSlugRoute
  BlogIndexRoute: typeof BlogIndexRoute
  BlogAutorSlugRoute: typeof BlogAutorSlugRoute
  BlogCategoriaSlugRoute: typeof BlogCategoriaSlugRoute
}

const BlogRouteChildren: BlogRouteChildren = {
  BlogSlugRoute: BlogSlugRoute,
  BlogIndexRoute: BlogIndexRoute,
  BlogAutorSlugRoute: BlogAutorSlugRoute,
  BlogCategoriaSlugRoute: BlogCategoriaSlugRoute,
}

const BlogRouteWithChildren = BlogRoute._addFileChildren(BlogRouteChildren)

interface SystemRouteChildren {
  SystemLaunchStatusRoute: typeof SystemLaunchStatusRoute
  SystemOpsStatusRoute: typeof SystemOpsStatusRoute
  SystemSchemaRoute: typeof SystemSchemaRoute
  SystemSecurityStatusRoute: typeof SystemSecurityStatusRoute
  SystemSetupRoute: typeof SystemSetupRoute
  SystemStatusRoute: typeof SystemStatusRoute
  SystemIndexRoute: typeof SystemIndexRoute
}

const SystemRouteChildren: SystemRouteChildren = {
  SystemLaunchStatusRoute: SystemLaunchStatusRoute,
  SystemOpsStatusRoute: SystemOpsStatusRoute,
  SystemSchemaRoute: SystemSchemaRoute,
  SystemSecurityStatusRoute: SystemSecurityStatusRoute,
  SystemSetupRoute: SystemSetupRoute,
  SystemStatusRoute: SystemStatusRoute,
  SystemIndexRoute: SystemIndexRoute,
}

const SystemRouteWithChildren =
  SystemRoute._addFileChildren(SystemRouteChildren)

interface CursoSlugRouteChildren {
  CursoSlugProvaRoute: typeof CursoSlugProvaRoute
}

const CursoSlugRouteChildren: CursoSlugRouteChildren = {
  CursoSlugProvaRoute: CursoSlugProvaRoute,
}

const CursoSlugRouteWithChildren = CursoSlugRoute._addFileChildren(
  CursoSlugRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  AdminRoute: AdminRouteWithChildren,
  BlogRoute: BlogRouteWithChildren,
  CadastroRoute: CadastroRoute,
  CatalogoRoute: CatalogoRoute,
  ConfiguracoesRoute: ConfiguracoesRoute,
  ConquistasRoute: ConquistasRoute,
  ContatoRoute: ContatoRoute,
  DashboardRoute: DashboardRoute,
  FaqRoute: FaqRoute,
  LoginRoute: LoginRoute,
  MinhasTrilhasRoute: MinhasTrilhasRoute,
  NotificacoesRoute: NotificacoesRoute,
  OnboardingRoute: OnboardingRoute,
  PerfilRoute: PerfilRoute,
  PlanoRoute: PlanoRoute,
  PlanosRoute: PlanosRoute,
  RecuperarSenhaRoute: RecuperarSenhaRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  SobreRoute: SobreRoute,
  SystemRoute: SystemRouteWithChildren,
  TrilhasRoute: TrilhasRoute,
  VitrineRoute: VitrineRoute,
  AulaSlugRoute: AulaSlugRoute,
  CertificadoCodeRoute: CertificadoCodeRoute,
  CursoSlugRoute: CursoSlugRouteWithChildren,
  InstrutorSlugRoute: InstrutorSlugRoute,
  ModuloSlugRoute: ModuloSlugRoute,
  TrilhaSlugRoute: TrilhaSlugRoute,
  ApiPublicWebhooksMercadoPagoRoute: ApiPublicWebhooksMercadoPagoRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
